# Generated by Django 5.2.5 on 2025-08-24 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='categories',
            name='mainCategory',
            field=models.ForeignKey(blank=True, help_text='Eğer bu kategori başka bir kategoriye bağlıysa burayı doldurunuz', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
    ]
