# Generated by Django 5.2.5 on 2025-08-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_categories_options_categories_maincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='seo_title',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
