# Generated by Django 5.2.5 on 2025-08-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
