# Generated by Django 5.2.5 on 2025-08-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='main_window_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Türk Lirası cinsinden giriniz', max_digits=10),
        ),
    ]
