# Generated by Django 5.2.5 on 2025-08-25 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_variations_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variations',
            name='parent_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variations'),
        ),
    ]
